package assignment2_databasewithgui;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;

/**
 *
 * @author Kawya
 */
public class AddBooks extends javax.swing.JFrame {

    /**
     * Creates new form addBooks
     */
    public static Home obj;
    public AddBooks(Home obj) {
        initComponents();
        this.obj = obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBooksLable = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bookNameLable = new javax.swing.JLabel();
        authorNameLabel = new javax.swing.JLabel();
        ISBNnumberLable = new javax.swing.JLabel();
        CourseLabel = new javax.swing.JLabel();
        bookNameText = new javax.swing.JTextField();
        authorText = new javax.swing.JTextField();
        ISBNText = new javax.swing.JTextField();
        courseText = new javax.swing.JTextField();
        referCheckBox = new javax.swing.JCheckBox();
        back = new javax.swing.JButton();
        add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Books");

        addBooksLable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addBooksLable.setText("Add Book");

        bookNameLable.setText("Book Name");

        authorNameLabel.setText("Author Name");

        ISBNnumberLable.setText("ISBN Number");

        CourseLabel.setText("Course");

        bookNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bookNameTextKeyPressed(evt);
            }
        });

        authorText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                authorTextKeyPressed(evt);
            }
        });

        ISBNText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ISBNTextKeyPressed(evt);
            }
        });

        courseText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                courseTextKeyPressed(evt);
            }
        });

        referCheckBox.setText("Reference Book");
        referCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referCheckBoxActionPerformed(evt);
            }
        });

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/back.png"))); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus.png"))); // NOI18N
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBooksLable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(authorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(39, 39, 39))
                                    .addComponent(bookNameLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ISBNnumberLable, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ISBNText, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(authorText)
                                    .addComponent(bookNameText)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CourseLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addComponent(referCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                        .addGap(104, 104, 104))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(courseText, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(29, 29, 29)))
                .addGap(55, 55, 55))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(addBooksLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNameLable)
                    .addComponent(bookNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(authorNameLabel)
                    .addComponent(authorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBNText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ISBNnumberLable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(referCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CourseLabel)
                    .addComponent(courseText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(add))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        try{
            obj.setIconImage(ImageIO.read(new File("book.png")));
        }
        catch(IOException ex){
            System.out.println("Error Logo"+ex);
        }
        this.dispose();
        
    }//GEN-LAST:event_backActionPerformed
    public void disableCourse(){
        courseText.setEnabled(false);
        
    }
    private void referCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referCheckBoxActionPerformed
        // TODO add your handling code here:
        if(referCheckBox.isSelected()){
            courseText.setEnabled(true);
        }
        else{
            courseText.setEnabled(false);
        }
        
    }//GEN-LAST:event_referCheckBoxActionPerformed

    private void bookNameTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bookNameTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            authorText.requestFocus();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN){
            authorText.requestFocus();
        }
        
    }//GEN-LAST:event_bookNameTextKeyPressed

    private void authorTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_authorTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            ISBNText.requestFocus();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
            bookNameText.requestFocus();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN){
            ISBNText.requestFocus();
        }
    }//GEN-LAST:event_authorTextKeyPressed

    private void ISBNTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ISBNTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER && referCheckBox.isSelected()) {
            courseText.requestFocus();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
            authorText.requestFocus();
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_DOWN && referCheckBox.isSelected()){
            courseText.requestFocus();
        }
    }//GEN-LAST:event_ISBNTextKeyPressed

    private void courseTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_courseTextKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            java.awt.event.ActionEvent ev =null;
            addActionPerformed(ev);
        }
        else if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_UP){
            ISBNText.requestFocus();
        }
    }//GEN-LAST:event_courseTextKeyPressed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        String bookName = bookNameText.getText();
        String authorName = authorText.getText();
        String ISBN = ISBNText.getText();
        String referBook = "No";
        String course = courseText.getText();
        if(referCheckBox.isSelected()){
            referBook = "Yes";

        }
        String loaned = "No";
        String loaner = "";
        String dueDate = "";
        
        
        Connection con1;
        PreparedStatement insert;
        
        AddBooks objbooks = new AddBooks(obj);
        
        if(bookNameText.getText().isEmpty()){
            JOptionPane.showMessageDialog(objbooks, "Enter Book Name !","ERROR: Fill all the Informations",JOptionPane.ERROR_MESSAGE);
        }
        else if(authorText.getText().isEmpty()){
            JOptionPane.showMessageDialog(objbooks, "Enter Author Name !","ERROR: ERROR: Fill all the Informations",JOptionPane.ERROR_MESSAGE);
        }
        else if(ISBNText.getText().isEmpty()){
            JOptionPane.showMessageDialog(objbooks, "Enter ISBN Number !","ERROR: ERROR: Fill all the Informations",JOptionPane.ERROR_MESSAGE);
        }
        else if(referCheckBox.isSelected() && courseText.getText().isEmpty()){
            JOptionPane.showMessageDialog(objbooks, "Enter Course Name !","ERROR: ERROR: Fill all the Informations",JOptionPane.ERROR_MESSAGE);
        }
        else{
            try {
                con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/assignment2_gui","root","");

                insert = con1.prepareStatement("insert into books(bookName ,authorName ,ISBN ,referBook ,course ,loaned ,loaner ,dueDate)values(?,?,?,?,?,?,?,?)");
                insert.setString(1, bookName);
                insert.setString(2, authorName);
                insert.setString(3, ISBN);
                insert.setString(4, referBook);
                insert.setString(5, course);
                insert.setString(6, loaned);
                insert.setString(7, loaner);
                insert.setString(8, dueDate);
                insert.executeUpdate();
                
                JOptionPane.showMessageDialog(objbooks, "Book Added !");
                bookNameText.setText("");
                authorText.setText("");
                ISBNText.setText("");
                courseText.setText("");
            }
            catch (SQLException ex) {
                Logger.getLogger(AddDVD.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Database Requrments Not Found...","Warning !",JOptionPane.WARNING_MESSAGE);
                bookNameText.setText("");
                authorText.setText("");
                ISBNText.setText("");
                courseText.setText("");
            }
           this.obj.booksTable_update();
        }
        
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBooks objnew = new AddBooks(obj);
                objnew.setVisible(true);
                objnew.disableCourse();
                try{
                    objnew.setIconImage(ImageIO.read(new File("book.png")));
                }
                catch(IOException ex){
                    System.out.println("Error Logo"+ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CourseLabel;
    private javax.swing.JTextField ISBNText;
    private javax.swing.JLabel ISBNnumberLable;
    private javax.swing.JButton add;
    private javax.swing.JLabel addBooksLable;
    private javax.swing.JLabel authorNameLabel;
    private javax.swing.JTextField authorText;
    private javax.swing.JButton back;
    private javax.swing.JLabel bookNameLable;
    private javax.swing.JTextField bookNameText;
    private javax.swing.JTextField courseText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox referCheckBox;
    // End of variables declaration//GEN-END:variables
}
